### ISSUE TITLE
Error at /graphql endpoint

### ISSUE THREAD

**Issue by jacobmishkin** [wp-graphql/wp-graphql#1188]
Full error:
"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:

Unexpected token < in JSON at position 0

Description: 
Unable to retrieve graphql endpoint looks like it's pulling HTML. Using Local for WP site. Gatsby setup: Gatsby starter theme. 

Steps to resolve the issue: 

Set Permalink to post name
flushed Permalinks
tried to version down gatsby-source-graphql to 2.1.25
used live link for local does not return a graphql endpoint: bf22ebfb.ngrok.io/graphql
WPGraphiql works in the WP install. 
normal Local url in browser with /graphql does return JSON. 

Setup: 
MacOS 
Local by flywheel

Gatsby setup: 
dependencies:
    "gatsby": "^2.19.45",
    "gatsby-image": "^2.2.44",
    "gatsby-plugin-manifest": "^2.2.48",
    "gatsby-plugin-offline": "^3.0.41",
    "gatsby-plugin-react-helmet": "^3.1.24",
    "gatsby-plugin-sharp": "^2.4.13",
    "gatsby-source-filesystem": "^2.1.56",
    "gatsby-source-graphql": "^2.1.35",
    "gatsby-transformer-sharp": "^2.3.19",
    "prop-types": "^15.7.2",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-helmet": "^5.2.1",
    "typescript": "^3.8.3"

Gatsby config.js: 

module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-source-graphql`,
      options: {
        typeName: `WPGraphQL`,
        fieldName: `wpgraphql`,
        url: `http://backend.jama/graphql`, //Custom Local url config.
        refetchInterval: 60,
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}

If anyone requires anymore info I'd be happy to provide it, Thanks.

**Comment by jacobmishkin** [comment]
This issue has been resolved. This error was not caused by wp-graphql plugin, but rather by Local. 

If you run into this issue, in Local go to Preferences -> Advanced -> Router Mode, and change to localhost. Add the Localhost url to the Gatsby config, and your schema should appear. 

Hope this helps anyone else running into this error.

**Comment by jasonbahl** [comment]
@jacobmishkin Thanks for the follow-up with the solution!

**Comment by spchand86** [comment]
@jacobmishkin While your given solution resolves the issue when pointing to the localhost URL for the wp instance, it is still not possible to use the live link graphql endpoint(which gives html response). Any suggestions for the same?

**Comment by Lmraza98** [comment]
@jacobmishkin I am having a similar issue! In my case, I'm running a headless Wordpress instance and nginx is routing it to /admin on my site'. I have the GraphQL plugin installed; while GraphiQL is working and querying correctly, I get a 404 page not found when clicking on the link ( http://site.com/graphql ) . Instead I expect to see something in JSON format, like: 
`
{"errors":[{"message":"GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\"","extensions":{"category":"request"}}],"extensions":{"debug":[]}}
`
I suspect this has something to do with my routing in nginx but I haven't been able to figure this one out.

`location /admin {
    add_header X-Frame-Options SAMEORIGIN;
    add_header Strict-Transport-Security "max-age=31536000";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    alias /home/lmraza98/wordpress/;
    try_files $uri $uri/ /index.php?$args;
    include  /etc/nginx/mime.types;

    location ~ \.php$ {
      include snippets/fastcgi-php.conf;
      fastcgi_param SCRIPT_FILENAME $request_filename;
      fastcgi_pass unix:/run/php/php7.4-fpm.sock;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
      expires max;
      log_not_found off;
    }
  }`

Anyone know how I could proxy this graphql route with nginx?

**Comment by kpsahani** [comment]
> @jacobmishkin Thanks for the follow-up with the solution!

Hello @jasonbahl, where can i find  Preferences -> Advanced -> Router Mode
so i can change please help me

**Comment by jasonbahl** [comment]
@kpsahani if you're using https://localwp.com/, the following video shows how to do this:

https://user-images.githubusercontent.com/1260765/129755724-20bcc6b1-3e2a-4a1f-9a3d-2d9daa613290.mov

**Comment by dcumpton** [comment]
> While your given solution resolves the issue when pointing to the localhost URL for the wp instance, it is still not possible to use the live link graphql endpoint(which gives html response). Any suggestions for the same?

@spchand86 If you are still looking for a solution to this, I was facing the same issue, and using this endpoint is working for me with Live Link: `https://my-live-link-url.localsite.io?graphql=true`

Reference: https://github.com/wp-graphql/wp-graphql/issues/213#issuecomment-877497336
