### ISSUE TITLE
Prevent "Password Changed" Emails on User Registration

### ISSUE THREAD

**Issue by kellenmace** [wp-graphql/wp-graphql#1201]
When you register a new user using WPGraphQL's `registerUser` mutation and set the user's password at the same time, the registered user will receive a "Password Changed" email.

This happens because WPGraphQL calls WordPress' `register_new_user()` function to save the new user's username and email, then calls WP's `wp_update_user()` function to save everything else (firstName, lastName, password, etc.). When WP runs a check inside of `wp_update_user()` to see if the new password matches the one on file previously (which it doesn't), it will trigger sending of the "Password Changed" email.

In my mind, this makes for a confusing experience for users, though. They'll likely think:

> I just registered as a user on this website, then I immediately got an email saying my password has been _changed_ -- what's the deal with that?

## Steps to Reproduce
Fire off this mutation and confirm that a "Password Changed" email is sent out:

```graphql
mutation {
  registerUser(
      input: {
        clientMutationId: "123"
        username: "123@example.com"
        firstName: "Test"
        lastName: "McTestUser"
        email: "123@example.com"
        password: "password"
      }
    ) {
      user {
        userId
      }
    }
}
```

## Solution
I propose we prevent "Password Changed" emails from being sent out during the user registration process.

We can disable the "Password Changed" emails immediately before WPGraphQL calls `wp_update_user()` inside of `UserRegister.php`, then re-enable it immediately afterward.

This will prevent "Password Changed" emails from being sent out when a user is registered via the `registerUser` mutation, but won't have any affect on those emails being sent out otherwise (such as when the user actually does change their password via a password reset flow).

 PR incoming!

**Comment by kellenmace** [comment]
One thought on the PR:
If the `send_password_change_email` filter has already, intentionally been hooked to `__return_false` on the site to prevent these emails, removing that filter could potentially be problematic, since for the rest of the request, it would no longer be hooked.

Alternatively, we could hook `send_password_change_email` to a method in the `UserRegister` class that just simply returns false to ensure that when the filter is removed, we're not affecting anything else. Whoever reviews this– please let me know if you'd rather go that route and I'll gladly update the PR.

Thanks!

**Comment by jasonbahl** [comment]
@kellenmace I left a thought on your PR. Untested, but I think it might work?

**Comment by kellenmace** [comment]
Thanks @jasonbahl! I updated the PR with a new approach and a test to accompany it. 👍🏼

**Comment by web-programmer-here** [comment]
@jasonbahl this is still happening, if I use RegisterUser mutation to register a user and set a password, I still get an email as king to set a password, is this related?
