### ISSUE TITLE
v0.10.0 breaks schema on WordPress Multisite

### ISSUE THREAD

**Issue by HumidBrains** [wp-graphql/wp-graphql#1354]
**Steps to reproduce:**

Note that I'm running a WP Multisite, so this might not be a problem for all.
I can reproduce this with no other plugins active and no Custom Post Types registered. 

1. Install WPGraphiQL Version: 1.0.1
2. Install WPGraphQL Version: 0.10.0
3. Open WPGraphiQL which now says "NO SCHEMA AVAILABLE"

**Expected behavior:**
Schema expected to show like it does with previous WPGraphQL v0.9.1

**Comment by jasonbahl** [comment]
@HumidBrains can you provide your PHP & WordPress versions?

**Comment by HumidBrains** [comment]
Sure @jasonbahl 
PHP 7.3.18
WordPress + Woo 5.4.2

**Comment by HumidBrains** [comment]
@jasonbahl I can give you super admin access via slack DM if you want to have a look. The site is in its infancy, so not much to hide yet ;) Let me know.

**Comment by jasonbahl** [comment]
Are there any PHP error logs? Things *should* work for multisite. We don’t explicitly support multisite but it *should* work fine for many use cases. I was testing on multisite just last week.

**Comment by HumidBrains** [comment]
No logs, but I can rerun the process with logging activated, then get back to you. 
Meanwhile, you're saying "should work fine for many use cases". Are there any limitations I should be aware of maybe? For me, it's beneficial with running a multisite, but if you'd advice against it, for sure I'd reconsider.

**Comment by jasonbahl** [comment]
@HumidBrains we've just not done much to optimize for multisite specifically. Like there are no network options exposed, no way to get a list of sites, etc. 

Each individual site in the network _should_ have it's own endpoint, but there's no special treatment or concept of a network endpoint that could get you access to many sites in the network from one Graph.

**Comment by jasonbahl** [comment]
@HumidBrains I just tried using local by flywheel on:
- PHP 7.3.5
- WordPress 5.4.2
- WPGraphQL v0.10.0
- WPGraphiQL v1.0.1

![Screen Shot 2020-06-30 at 9 34 18 AM](https://user-images.githubusercontent.com/1260765/86146146-1016d480-bab5-11ea-8816-e82c0d3d7272.png)

And I'm able to see the Schema in GraphiQL:

![Screen Shot 2020-06-30 at 9 36 04 AM](https://user-images.githubusercontent.com/1260765/86146200-258bfe80-bab5-11ea-91ca-226def82dfec.png)

**Comment by MKlblangenois** [comment]
Hello!

I had the same issue and deactivate WPGraphQL JWAT Authentification has solve my issue. Maybe try to deactivate some plugins on your side ?

**Comment by jasonbahl** [comment]
@MKlblangenois I'll look into getting WPGraphQL JWT updated to not have conflicts with v0.10.0. Thanks for pointing that out.

**Comment by jasonbahl** [comment]
@MKlblangenois do you have more details about how WPGraphQL JWT Authentication is breaking with v0.10.0 release? I'm using them together right now and I'm not experiencing any issues. Are there specific requests that are causing issues?

Below is a screen recording of logging in then using the authToken in the headers of another request to get private data. 

![login-mutation-wpgraphql-v0 10 0](https://user-images.githubusercontent.com/1260765/86154391-3f7f0e80-bac0-11ea-92d2-27d6a29aecf3.gif)

Using: 

- PHP 7.4.1
- WordPress 5.4.2
- WPGraphQL v0.10.0
- WPGraphQL JWT Authentication v0.4.1

**Comment by jasonbahl** [comment]
@HumidBrains fixed in the v0.10.1 release

https://github.com/wp-graphql/wp-graphql/releases/tag/v0.10.1

**Comment by MKlblangenois** [comment]
@jasonbahl Unfortunately no, I've tried on a fresh install with Local and I got an `internal server error` with no information about "debug" message like in your record and no error from WP.

- PHP 7.3.5
- WordPress 5.4.2
- WPGraphQL v0.10.1
- WPGraphQL JWT Authentication v0.4.1
- WPGraphiQL v1.0.1

**Comment by HumidBrains** [comment]
@jasonbahl, like @MKlblangenois  I can confirm the problem remains when WPGraphQL JWT Authentication v0.4.1 is active. 

`{errors: [{message: "Internal server error", extensions: {category: "internal"}}]}
errors: [{message: "Internal server error", extensions: {category: "internal"}}]
0: {message: "Internal server error", extensions: {category: "internal"}}
extensions: {category: "internal"}
category: "internal"
message: "Internal server error"`

Here is my plugin list. For me, WPGraphiQL runs as expected unless WPGraphQL JWT Authentication gets activated, so at least it seems like we're one step closer ;)

+-------------------------------------+----------------+------------------------------+---------+
| name                                | status         | update                       | version |
+-------------------------------------+----------------+------------------------------+---------+
| admin-columns-pro                   | active-network | none                         | 5.2     |
| ac-addon-acf                        | active-network | none                         | 2.6.1   |
| ac-addon-woocommerce                | active-network | none                         | 3.5     |
| admin-custom-font                   | active-network | none                         | 2.5.1   |
| adminimize                          | active-network | none                         | 1.11.6  |
| admin-pulse                         | active-network | none                         | 1.1.0   |
| advanced-custom-fields-pro          | active-network | none                         | 5.8.12  |
| custom-post-type-ui                 | active-network | none                         | 1.7.4   |
| cptui-extended                      | active-network | none                         | 1.5.3   |
| disable-gutenberg                   | inactive       | none                         | 2.1     |
| duplicate-post                      | active-network | none                         | 3.2.4   |
| facebook-for-woocommerce            | inactive       | none                         | 1.11.4  |
| kliken-marketing-for-google         | active         | none                         | 1.0.4   |
| happyfiles-pro                      | active-network | none                         | 1.1.1   |
| wp-jamstack-deployments             | active-network | none                         | 1.0.0   |
| mailchimp-for-woocommerce           | active         | none                         | 2.4.1   |
| multisite-enhancements              | active-network | none                         | 1.5.2   |
| multisite-toolbar-additions         | active-network | none                         | 2.0.1   |
| network-media-library               | active-network | none                         | 1.5.0   |
| regenerate-thumbnails               | active-network | none                         | 3.1.3   |
| sg-cachepress                       | active-network | none                         | 5.5.7   |
| timber-library                      | active-network | none                         | 1.16.0  |
| woocommerce                         | active-network | none                         | 4.2.2   |
| wp-multisite-content-copier         | active-network | none                         | 1.4.0   |
| wp-multisite-user-sync              | active-network | none                         | 1.2.0   |
| wp-gatsby                           | active-network | version higher than expected | 0.4.1   |
| wp-graphiql                         | active-network | none                         | 1.0.1   |
| wp-graphql-0.10.1                   | active-network | none                         | 0.10.1  |
| wp-graphql-custom-post-type-ui      | active-network | none                         | 1.1     |
| wp-graphql-acf                      | active-network | none                         | 0.3.4   |
| wp-graphql-gutenberg-0.3.4          | active-network | none                         | 0.3.4   |
| wp-graphql-gutenberg-acf-0.3.0      | active-network | none                         | 0.3.0   |
| wp-graphql-jwt-authentication-0.4.1 | inactive       | none                         | 0.4.1   |
| wp-graphql-woocommerce              | active-network | none                         | 0.5.1   |
| wp-graphql-yoast-seo                | active-network | none                         | 4.1.0   |
| wordpress-seo                       | active-network | none                         | 14.4.1  |
+-------------------------------------+----------------+------------------------------+---------+

**Comment by thakkaryash94** [comment]
Happened with me as well. In my case, I forgot to complete the plugin after installation steps. https://github.com/wp-graphql/wp-graphql-jwt-authentication#install-activate--setup
