### ISSUE TITLE
Ensure all fields in the Schema have a description

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#1790]
Currently there are several fields in the Schema that are missing descriptions. 

See: https://github.com/wp-graphql/wp-graphql/runs/2137137486?check_suite_focus=true

We should fix that.

**Comment by szepeviktor** [comment]
After it is done please consider de-neutralizing the schema linter CI job.

**Comment by szepeviktor** [comment]
@jasonbahl Currently there is a Syntax Error in the schema.
https://github.com/wp-graphql/wp-graphql/runs/2152887244?check_suite_focus=true
Has it been released to the public?

**Comment by jasonbahl** [comment]
> Currently there is a Syntax Error in the schema

@szepeviktor ah ya, that was fixed. I made a foolish mistake by adjusting how the built-in Post Types and Taxonomies were being registered to the Schema and it caused some issues, including issues with the static schema generation for linting. Fixed it quickly in `v1.3.1` and we're back in business.

Thanks to @markkelnar work, we're getting close to being able to actually turn on the linter! 👏

**Comment by szepeviktor** [comment]
I see.

> field must return a non-null `PageInfo` object not `WPPageInfo`

We are down to a few of the above. Maybe tell schema linter to ignore these...

---

[off] If you hook heavy code you could make WordPress run much faster with HookProxy: https://github.com/szepeviktor/Toolkit4WP/blob/master/src/HookProxy.php

**Comment by markkelnar** [comment]
Thinking this issue be closed since descriptions have been added. The schema linter still throws errors related to the PageInfo issue. Maybe make a different issue for that specifically?

**Comment by jasonbahl** [comment]
@markkelnar yes, I think that's a good call. 

If we can configure the linter to ignore that rule, we can enable the linter to pass/fail going forward, and follow-up with the `PageInfo` rule with a separate issue. 

We can probably even make those 2 separate issues: 
- Enable Schema Linter to pass/fail (ignoring PageInfo) rule"
- "Add PageInfo rule back to Schema Linter (and properly support `PageInfo` in the Schema")

**Comment by jasonbahl** [comment]
Closed by #1851
