### ISSUE TITLE
Pagination not working for pageBy and taxQuery queries

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql#861]
So I have the following query:

```
query DivisionQuery($first: Int, $after: String) {
  pageBy(uri: "what-we-do/visual-effects/") {
    title
    childPages(first: $first, after: $after, where: {orderby: [{field: MENU_ORDER, order: ASC}]}) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        title
      }
    }
  }
}
// Variables
{
  "first": 1,
  "after": null
}
```

Which gives me this result:
```
{
  "data": {
    "pageBy": {
      "title": "Visual Effects",
      "childPages": {
        "pageInfo": {
          "hasNextPage": true,
          "endCursor": "YXJyYXljb25uZWN0aW9uOjU4OQ=="
        },
        "nodes": [
          {
            "title": "Adidas &#8211; Creators"
          }
        ]
      }
    }
  }
}
```

So I do the next query, with `after` set to the `endCursor`:
```
// Variables
{
  "first": 1,
  "after": "YXJyYXljb25uZWN0aW9uOjU4OQ=="
}
```

But the result is:
```
{
  "data": {
    "pageBy": {
      "title": "Visual Effects",
      "childPages": {
        "pageInfo": {
          "hasNextPage": false,
          "endCursor": null
        },
        "nodes": []
      }
    }
  }
}
```

It should actually give me the next page. If I run the first query with `first: 2` and `after: null` I get the right pages, with a result like this:
```
{
  "data": {
    "pageBy": {
      "title": "Visual Effects",
      "childPages": {
        "pageInfo": {
          "hasNextPage": true,
          "endCursor": "YXJyYXljb25uZWN0aW9uOjE0Mjg="
        },
        "nodes": [
          {
            "title": "Adidas &#8211; Creators"
          },
          {
            "title": "Superbowl 2018"
          }
        ]
      }
    }
  }
}
```

I haven't been able to get pagination to work with `taxQuery` plugin either, so I wonder if I'm doing this right at all?

**Comment by jasonbahl** [comment]
@drewbaker there’s a bug right now with pagination and custom ordering. 

Spent some time last night digging on it. Have it partially resolved but still have some work to do. 

You can read a bit more here: https://github.com/wp-graphql/wp-graphql/issues/818#issuecomment-494658800

**Comment by jasonbahl** [comment]
@drewbaker this actually might not be related to #818 

From what I can tell, this is working fine. Curious if there's a plugin at some level causing some conflict like resetting a global improperly or something like that 🤔 

Here's a look at my setup:

![Screen Shot 2019-05-22 at 9 44 31 PM](https://user-images.githubusercontent.com/1260765/58224417-f6fcfb00-7cda-11e9-9014-c2a9e42a51b1.png)

And here's a look at the same query (adjusted for my data) with pagination working as expected:

![childrenPagePagination](https://user-images.githubusercontent.com/1260765/58224447-16942380-7cdb-11e9-9076-445851eacfdb.gif)

**Comment by jasonbahl** [comment]
@drewbaker ok. . .actually, I've verified the bug on the latest release but NOT in develop. . .so one of the bugs that's been fixed in develop fixes this. 

Can you confirm latest `develop` works for you?

I'll try to get a release out shortly.

**Comment by drewbaker** [comment]
OK, so I installed develop just now and it still doesn't work when requesting a deep URI like `work/page`, if it's just `work` then it does work, but in the wrong order.

**Comment by drewbaker** [comment]
Just tried this with version `0.3.4` and it still doesn't work. I recorded my screen showing this not working and the plugins I have active (only WP-GQL and ACF). My suspicion is because my page URI is two levels deep.

Screen recording here: https://www.dropbox.com/s/6bniq5p6uxrvv6b/wp-gql-pagination-broken.mov?dl=0
